trigger:
  branches:
    include:
      - main

schedules:
  - cron: "0 8 * * *"
    displayName: Daily Scheduled Build
    branches:
      include:
        - main

jobs:
  - job: Build
    displayName: 'Build and Test Java Project'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - task: Checkout@v2
        displayName: 'Checkout code'

      - task: UseJavaVersion@1
        displayName: 'Set up JDK 22'
        inputs:
          version: '22'
          distribution: 'temurin'

      - task: UseMavenVersion@1
        displayName: 'Set up Maven'
        inputs:
          mavenVersion: '3.9.6'

      - script: |
          curl -o allure-2.25.0.tgz -OLs https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.25.0/allure-commandline-2.25.0.tgz
          sudo tar -zxvf allure-2.25.0.tgz -C /opt/
          sudo ln -s /opt/allure-2.25.0/bin/allure /usr/bin/allure
          allure --version
        displayName: 'Install Allure CLI'

      - script: |
          mvn clean test
        displayName: 'Test with Maven'

      - script: |
          allure generate target/allure-results --single-file --clean -o target/allure-report
        displayName: 'Generate Allure Report'

      - task: PublishPipelineArtifact@1
        displayName: 'Upload Allure Report'
        inputs:
          targetPath: '$(System.DefaultWorkingDirectory)/target/allure-report/index.html'
          artifact: 'allure-report'
