name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 22
      uses: actions/setup-java@v3
      with:
        java-version: '22'
        distribution: 'temurin'
    
    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
          maven-version: 3.9.6

    - name: Set up Allure
      uses: allure-framework/allure-action@v2.24.0
        
    - name: Test with Maven
      continue-on-error: true
      run: mvn clean test

    - name: Generate Allure Report in target/
      run: |
        cd target/
        allure generate allure-results --single-file --clean -o allure-report
